-- Phase 1: richer RA bills (Zoho-style) — line items + GST/TDS/retention/advance + numbering
ALTER TABLE bills ADD COLUMN IF NOT EXISTS bill_number TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS bill_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS vendor_id INTEGER;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS ra_number INTEGER;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sub_total REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS cgst REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sgst REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS igst REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS gst_total REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS gst_rate REAL DEFAULT 18;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS tds_section TEXT DEFAULT '194C';
ALTER TABLE bills ADD COLUMN IF NOT EXISTS tds_rate REAL DEFAULT 2;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS retention_pct REAL DEFAULT 5;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS advance_recovery REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS other_deductions REAL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS deduction_reason TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS amount_in_words TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS bill_line_items (
  id SERIAL PRIMARY KEY,
  bill_id INTEGER NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
  boq_id INTEGER,
  description TEXT,
  unit TEXT,
  hsn_code TEXT,
  quantity REAL DEFAULT 0,
  rate REAL DEFAULT 0,
  amount REAL DEFAULT 0,
  sort_order INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_bli_bill ON bill_line_items(bill_id);
CREATE INDEX IF NOT EXISTS idx_bli_boq ON bill_line_items(boq_id);
