#!/usr/bin/env node
/* Writes the product film's copy of the built-in roles from the backend's
   own table (backend/shared/roles.js), so the team-and-roles chapter shows
   each role exactly what the app would. Run after changing a role:

     npm run film:roles

   scripts/check-film.mjs fails if the copy and the backend disagree. */
const fs = require('fs');
const path = require('path');
const roles = require(path.resolve(__dirname, '..', '..', '..', 'backend', 'shared', 'roles.js'));

const FILM_ROLES = ['Owner', 'Sales', 'Procurement', 'Production', 'Finance', 'Viewer'];
const out = {};
for (const r of FILM_ROLES) {
  const p = roles.permissionsFor(r);
  out[r] = { label: p.label, permissions: p.permissions };
}
const file = path.resolve(__dirname, '..', '..', 'src', 'components', 'marketing', 'film', 'data', 'roles.snapshot.js');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, `/* GENERATED by scripts/film/sync-roles.cjs from backend/shared/roles.js.
   Do not edit — change the role there and run \`npm run film:roles\`. */
export const ROLES = ${JSON.stringify(out, null, 2)};

export const RESOURCE_LABELS = ${JSON.stringify(roles.RESOURCES, null, 2)};
`);
console.log(`wrote ${path.relative(process.cwd(), file)} (${FILM_ROLES.join(', ')})`);
